spring:
  datasource:
    url: jdbc:h2:C:/triple_works/replymileageapi # 1회 실행, db 파일 생성
    #url: jdbc:h2:tcp://localhost/C:/triple_works/replymileageapi

    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true


logging:
  level:
    org.hibernate.sql: debug
    #org.hibernate.type: trace